export const climas = [
  {
    brand: "tcl",
    type: "elite",
    kw: 2.6,
    price: 232410,
    heater: false,
    capacity: 22,
    energy: "A++",
    guarntie: "3 év",
    src: "../pics/climasPics/tclelite.png",
    description: `Elegáns megjelenése bármely otthonba illik. Kényelmi funkciók sokasága, mint az I feel, az I set, a Smart Air Flow vagy az Anti cold air gondoskodik a felhasználónak leginkább megfelelő hőérzetről, a beépített hűtőközeg-szivárgás érzékelő pedig a biztonságról. 4in1 szűrő, öntisztító és sterilizáló funkció felel a levegő tisztaságáért. A készülékben WiFi előkészítés található.`,
  },
  {
    brand: "tcl",
    type: "thermo - x",
    kw: 2.6,
    price: 276860,
    heater: true,
    capacity: 22,
    src: "../pics/climasPics/tclthermox.png",
    energy: "A++",
    guarntie: "3 év",
    description: `Matt panelje kiemeli a többi klíma közül. A légbefúvás olyan egyenletes, mint egy lágy fuvallat, a 4 irányú légtereléssel együtt kiemelkedö a komfortérzet akár hüt akár fűt. 4in1 szürö gondoskodik a levegö tisztaságáról. A beépített wifi-nek a köszönhetöen akár okos otthonba is kapcsolható.`,
  },
  {
    brand: "tcl",
    type: "fresh-in",
    kw: 2.7,
    price: 330200,
    heater: true,
    capacity: 22,
    src: "../pics/climasPics/tclfreshin.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Ezüst színű panelje elegáns, speciális kialakításával akár 60m3 friss levegőt fúj be a helyiségbe óránként, melyet hűt vagy fűt a készülék. A levegő minőségéről QuadruPuri szűrőrendszer gondoskodik. A 14 S alakú légterelő lamellán található 1422 mikro méretű lyuknak és a 4 irányú légterelésnek köszönhetően a légbefúvás olyan, mint egy lágy fuvallat. Kiváló fűtésre is, ráadásul a beépített WiFivel akár okosotthonba is kapcsolható.`,
  },
  {
    brand: "cascade",
    type: "bora",
    kw: 2.5,
    price: 254000,
    heater: false,
    capacity: 22,
    src: "../pics/climasPics/cascadebora.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Bora klímaberendezés G10 GREE inverter technológiával biztosítja Önnek a csendes és energiatakarékos működést. Wi-Fi távvezérléssel, éjszakai üzemmóddal,távirányítóba épített hőmérővel (I Feel üzemmód) és sok további kényelmi funkcióval kényezteti használóját.`,
  },
  {
    brand: "cascade",
    type: "vision nordic",
    kw: 2.7,
    price: 312420,
    heater: true,
    capacity: 22,
    src: "../pics/climasPics/cascadevisionnordic.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Vision Nordic ami még a Sarkvidéken is megállná a helyét, mivel akár -25C° esetén is fűt! A fűtött csepptálca és a -25C° tartós külső hőmérséklet esetén is stabil működés gondoskodik arról, hogy ez a modell valóban 4 évszak legjobb választása legyen. Számos kényelmi funkció, mint az I feel funkció, az automatikus tisztítás és a WiFi vezérlés mellett a berendezés a 4 irányú légterelés segítségével biztosítja azt, hogy a helyiség egyenletes hűtésével kiemelkedő legyen komfortérzet.`,
  },
  {
    brand: "cascade",
    type: "black art",
    kw: 2.6,
    price: 275590,
    heater: false,
    capacity: 22,
    src: "../pics/climasPics/cascadeblackart.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Black Art klímaberendezés modern formatervezésű beltéri egysége bármilyen környezethez illik. A Cascade mindazokat az előnyöket nyújtják Önnek, amiket a legrangosabb klímamárkák kínálnak. A legújabb technológia, kiváló minőségű, tartós alkatrészek, elvárásokon túlmutató energiatakarékosság, alacsony zajszint, egészséges, biztonságos levegőminőség. `,
  },
  {
    brand: "cascade",
    type: "legend champagne",
    kw: 2.7,
    price: 358140,
    heater: true,
    capacity: 22,
    src: "../pics/climasPics/cascadelegend.png",
    energy: "A+++",
    guarntie: "5 év",
    description: `A Cascade Legend ami a különleges pezsgőszínű dizájn mellett tudásával is felhívja magára a figyelmet. A+++ energiabesorolása garantálja, hogy a klímával való fűtés tényleg nem luxus többé. A WiFi Smart alkalmazás segítségével egy okostelefon segítségével bármikor bárhonnan vezérelhető a készülék.`,
  },
  {
    brand: "lg",
    type: "silence",
    kw: 2.5,
    price: 259080,
    heater: false,
    capacity: 22,
    src: "../pics/climasPics/lgsilence.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Az LG Silence légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "lg",
    type: "artcool",
    kw: 2.5,
    price: 426720,
    heater: false,
    capacity: 22,
    src: "../pics/climasPics/lgartcool.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `A grafit színű beltéri egységgel rendelkező légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "lg",
    type: "artcool gallery",
    kw: 2.5,
    price: 646430,
    heater: false,
    capacity: 22,
    src: "../pics/climasPics/lgartcoolgalery.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Az LG Artcool Gallery egy stílusos megjelenésű készülék, ami lehetővé teszi Önnek, hogy a cserélhető képpel igazán egyedi klimája legyen. Emellett akár 70%-os energiamegtakaritást tesz lehetővé. `,
  },
  {
    brand: "lg",
    type: "artcool bézs",
    kw: 2.5,
    price: 520700,
    heater: false,
    capacity: 22,
    src: "../pics/climasPics/lgartcoolbezs.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `A bézs színű beltéri egységgel rendelkező légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "tcl",
    type: "elite",
    kw: 3.4,
    price: 250190,
    heater: false,
    capacity: 36,
    energy: "A++",
    guarntie: "3 év",
    src: "../pics/climasPics/tclelite.png",
    description: `Elegáns megjelenése bármely otthonba illik. Kényelmi funkciók sokasága, mint az I feel, az I set, a Smart Air Flow vagy az Anti cold air gondoskodik a felhasználónak leginkább megfelelő hőérzetről, a beépített hűtőközeg-szivárgás érzékelő pedig a biztonságról. 4in1 szűrő, öntisztító és sterilizáló funkció felel a levegő tisztaságáért. A készülékben WiFi előkészítés található.`,
  },
  {
    brand: "tcl",
    type: "thermo - x",
    kw: 3.4,
    price: 295910,
    heater: true,
    capacity: 36,
    src: "../pics/climasPics/tclthermox.png",
    energy: "A++",
    guarntie: "3 év",
    description: `Matt panelje kiemeli a többi klíma közül. A légbefúvás olyan egyenletes, mint egy lágy fuvallat, a 4 irányú légtereléssel együtt kiemelkedö a komfortérzet akár hüt akár fűt. 4in1 szürö gondoskodik a levegö tisztaságáról. A beépített wifi-nek a köszönhetöen akár okos otthonba is kapcsolható.`,
  },
  {
    brand: "tcl",
    type: "fresh-in",
    kw: 3.6,
    price: 355600,
    heater: true,
    capacity: 36,
    src: "../pics/climasPics/tclfreshin.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Ezüst színű panelje elegáns, speciális kialakításával akár 60m3 friss levegőt fúj be a helyiségbe óránként, melyet hűt vagy fűt a készülék. A levegő minőségéről QuadruPuri szűrőrendszer gondoskodik. A 14 S alakú légterelő lamellán található 1422 mikro méretű lyuknak és a 4 irányú légterelésnek köszönhetően a légbefúvás olyan, mint egy lágy fuvallat. Kiváló fűtésre is, ráadásul a beépített WiFivel akár okosotthonba is kapcsolható.`,
  },
  {
    brand: "cascade",
    type: "bora",
    kw: 3.2,
    price: 280670,
    heater: false,
    capacity: 36,
    src: "../pics/climasPics/cascadebora.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Bora klímaberendezés G10 GREE inverter technológiával biztosítja Önnek a csendes és energiatakarékos működést. Wi-Fi távvezérléssel, éjszakai üzemmóddal,távirányítóba épített hőmérővel (I Feel üzemmód) és sok további kényelmi funkcióval kényezteti használóját.`,
  },
  {
    brand: "cascade",
    type: "vision nordic",
    kw: 3.5,
    price: 340360,
    heater: true,
    capacity: 36,
    src: "../pics/climasPics/cascadevisionnordic.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Vision Nordic ami még a Sarkvidéken is megállná a helyét, mivel akár -25C° esetén is fűt! A fűtött csepptálca és a -25C° tartós külső hőmérséklet esetén is stabil működés gondoskodik arról, hogy ez a modell valóban 4 évszak legjobb választása legyen. Számos kényelmi funkció, mint az I feel funkció, az automatikus tisztítás és a WiFi vezérlés mellett a berendezés a 4 irányú légterelés segítségével biztosítja azt, hogy a helyiség egyenletes hűtésével kiemelkedő legyen komfortérzet.`,
  },
  {
    brand: "cascade",
    type: "black art",
    kw: 3.5,
    price: 313690,
    heater: false,
    capacity: 36,
    src: "../pics/climasPics/cascadeblackart.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Black Art klímaberendezés modern formatervezésű beltéri egysége bármilyen környezethez illik. A Cascade mindazokat az előnyöket nyújtják Önnek, amiket a legrangosabb klímamárkák kínálnak. A legújabb technológia, kiváló minőségű, tartós alkatrészek, elvárásokon túlmutató energiatakarékosság, alacsony zajszint, egészséges, biztonságos levegőminőség. `,
  },
  {
    brand: "cascade",
    type: "legend champagne",
    kw: 3.5,
    price: 384810,
    heater: true,
    capacity: 36,
    src: "../pics/climasPics/cascadelegend.png",
    energy: "A+++",
    guarntie: "5 év",
    description: `A Cascade Legend ami a különleges pezsgőszínű dizájn mellett tudásával is felhívja magára a figyelmet. A+++ energiabesorolása garantálja, hogy a klímával való fűtés tényleg nem luxus többé. A WiFi Smart alkalmazás segítségével egy okostelefon segítségével bármikor bárhonnan vezérelhető a készülék.`,
  },
  {
    brand: "lg",
    type: "silence",
    kw: 3.5,
    price: 379730,
    heater: false,
    capacity: 36,
    src: "../pics/climasPics/lgsilence.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Az LG Silence légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "lg",
    type: "artcool",
    kw: 5.0,
    price: 607060,
    heater: false,
    capacity: 55,
    src: "../pics/climasPics/lgartcool.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `A grafit színű beltéri egységgel rendelkező légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "lg",
    type: "artcool gallery",
    kw: 3.5,
    price: 679450,
    heater: false,
    capacity: 36,
    src: "../pics/climasPics/lgartcoolgalery.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Az LG Artcool Gallery egy stílusos megjelenésű készülék, ami lehetővé teszi Önnek, hogy a cserélhető képpel igazán egyedi klimája legyen. Emellett akár 70%-os energiamegtakaritást tesz lehetővé. `,
  },
  {
    brand: "lg",
    type: "artcool bézs",
    kw: 3.5,
    price: 538480,
    heater: false,
    capacity: 36,
    src: "../pics/climasPics/lgartcoolbezs.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `A bézs színű beltéri egységgel rendelkező légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "tcl",
    type: "elite",
    kw: 5.1,
    price: 364490,
    heater: false,
    capacity: 55,
    energy: "A++",
    guarntie: "3 év",
    src: "../pics/climasPics/tclelite.png",
    description: `Elegáns megjelenése bármely otthonba illik. Kényelmi funkciók sokasága, mint az I feel, az I set, a Smart Air Flow vagy az Anti cold air gondoskodik a felhasználónak leginkább megfelelő hőérzetről, a beépített hűtőközeg-szivárgás érzékelő pedig a biztonságról. 4in1 szűrő, öntisztító és sterilizáló funkció felel a levegő tisztaságáért. A készülékben WiFi előkészítés található.`,
  },
  {
    brand: "tcl",
    type: "thermo - x",
    kw: 5.1,
    price: 406400,
    heater: true,
    capacity: 55,
    src: "../pics/climasPics/tclthermox.png",
    energy: "A++",
    guarntie: "3 év",
    description: `Matt panelje kiemeli a többi klíma közül. A légbefúvás olyan egyenletes, mint egy lágy fuvallat, a 4 irányú légtereléssel együtt kiemelkedö a komfortérzet akár hüt akár fűt. 4in1 szürö gondoskodik a levegö tisztaságáról. A beépített wifi-nek a köszönhetöen akár okos otthonba is kapcsolható.`,
  },
  {
    brand: "cascade",
    type: "bora",
    kw: 4.6,
    price: 407670,
    heater: false,
    capacity: 55,
    src: "../pics/climasPics/cascadebora.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Bora klímaberendezés G10 GREE inverter technológiával biztosítja Önnek a csendes és energiatakarékos működést. Wi-Fi távvezérléssel, éjszakai üzemmóddal,távirányítóba épített hőmérővel (I Feel üzemmód) és sok további kényelmi funkcióval kényezteti használóját.`,
  },
  {
    brand: "cascade",
    type: "vision nordic",
    kw: 5.2,
    price: 466090,
    heater: true,
    capacity: 55,
    src: "../pics/climasPics/cascadevisionnordic.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Vision Nordic ami még a Sarkvidéken is megállná a helyét, mivel akár -25C° esetén is fűt! A fűtött csepptálca és a -25C° tartós külső hőmérséklet esetén is stabil működés gondoskodik arról, hogy ez a modell valóban 4 évszak legjobb választása legyen. Számos kényelmi funkció, mint az I feel funkció, az automatikus tisztítás és a WiFi vezérlés mellett a berendezés a 4 irányú légterelés segítségével biztosítja azt, hogy a helyiség egyenletes hűtésével kiemelkedő legyen komfortérzet.`,
  },
  {
    brand: "cascade",
    type: "black art",
    kw: 5.1,
    price: 416560,
    heater: false,
    capacity: 55,
    src: "../pics/climasPics/cascadeblackart.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Black Art klímaberendezés modern formatervezésű beltéri egysége bármilyen környezethez illik. A Cascade mindazokat az előnyöket nyújtják Önnek, amiket a legrangosabb klímamárkák kínálnak. A legújabb technológia, kiváló minőségű, tartós alkatrészek, elvárásokon túlmutató energiatakarékosság, alacsony zajszint, egészséges, biztonságos levegőminőség. `,
  },
  {
    brand: "lg",
    type: "silence",
    kw: 5.0,
    price: 566420,
    heater: false,
    capacity: 55,
    src: "../pics/climasPics/lgsilence.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Az LG Silence légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "lg",
    type: "artcool bézs",
    kw: 5.0,
    price: 730250,
    heater: false,
    capacity: 55,
    src: "../pics/climasPics/lgartcoolbezs.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `A bézs színű beltéri egységgel rendelkező légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "tcl",
    type: "elite",
    kw: 6.8,
    price: 444500,
    heater: false,
    capacity: 70,
    energy: "A++",
    guarntie: "3 év",
    src: "../pics/climasPics/tclelite.png",
    description: `Elegáns megjelenése bármely otthonba illik. Kényelmi funkciók sokasága, mint az I feel, az I set, a Smart Air Flow vagy az Anti cold air gondoskodik a felhasználónak leginkább megfelelő hőérzetről, a beépített hűtőközeg-szivárgás érzékelő pedig a biztonságról. 4in1 szűrő, öntisztító és sterilizáló funkció felel a levegő tisztaságáért. A készülékben WiFi előkészítés található.`,
  },
  {
    brand: "cascade",
    type: "bora",
    kw: 6.2,
    price: 495300,
    heater: false,
    capacity: 70,
    src: "../pics/climasPics/cascadebora.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Bora klímaberendezés G10 GREE inverter technológiával biztosítja Önnek a csendes és energiatakarékos működést. Wi-Fi távvezérléssel, éjszakai üzemmóddal,távirányítóba épített hőmérővel (I Feel üzemmód) és sok további kényelmi funkcióval kényezteti használóját.`,
  },
  {
    brand: "cascade",
    type: "vision nordic",
    kw: 7.1,
    price: 567690,
    heater: true,
    capacity: 70,
    src: "../pics/climasPics/cascadevisionnordic.png",
    energy: "A++",
    guarntie: "5 év",
    description: `A Cascade Vision Nordic ami még a Sarkvidéken is megállná a helyét, mivel akár -25C° esetén is fűt! A fűtött csepptálca és a -25C° tartós külső hőmérséklet esetén is stabil működés gondoskodik arról, hogy ez a modell valóban 4 évszak legjobb választása legyen. Számos kényelmi funkció, mint az I feel funkció, az automatikus tisztítás és a WiFi vezérlés mellett a berendezés a 4 irányú légterelés segítségével biztosítja azt, hogy a helyiség egyenletes hűtésével kiemelkedő legyen komfortérzet.`,
  },
  {
    brand: "lg",
    type: "silence",
    kw: 6.6,
    price: 753110,
    heater: false,
    capacity: 70,
    src: "../pics/climasPics/lgsilence.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `Az LG Silence légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
  {
    brand: "lg",
    type: "artcool bézs",
    kw: 6.6,
    price: 781050,
    heater: false,
    capacity: 70,
    src: "../pics/climasPics/lgartcoolbezs.png",
    energy: "A+++",
    guarntie: "3 év",
    description: `A bézs színű beltéri egységgel rendelkező légkondicionáló akár 70%-os energiamegtakaritást tesz lehetővé amellett, hogy hosszabb élettartamot és csendesebb működést biztosít Önnek. Számos funkció gondoskodik az Ön kényelméről, az automatikus tisztítás pedig megakadályozza, hogy penész és baktérium telepedjen meg a készülékében. `,
  },
];
